// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	ID              int32            `json:"id"`
	SenderAddress   string           `json:"sender_address"`
	ReceiverAddress string           `json:"receiver_address"`
	Amount          pgtype.Numeric   `json:"amount"`
	Timestamp       pgtype.Timestamp `json:"timestamp"`
}

type Wallet struct {
	ID        int32            `json:"id"`
	Address   string           `json:"address"`
	Balance   pgtype.Numeric   `json:"balance"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
